# Generated by Django 3.2.25 on 2025-03-25 07:48

import anim_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim_app', '0005_alter_viewhistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', validators=[anim_app.validators.validate_file_extension], verbose_name='Видео файл'),
        ),
    ]
