# Generated by Django 3.2.25 on 2025-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim_app', '0007_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnails/thumbnail.png', null=True, upload_to='thumbnails/%Y/%m/%d/', verbose_name='Обложка видео'),
        ),
    ]
