# Generated by Django 3.2.25 on 2025-03-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anim_app', '0009_alter_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
