# Generated by Django 3.2.25 on 2025-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim_app', '0010_remove_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='videos', to='anim_app.Category', verbose_name='Категория'),
        ),
    ]
